# Site
repository: Pitrick3141/Pitrick3141.github.io
favicon: images/CV.ico

# Content configuration version
version: 2

# Personal info
name: Yichen Wang
title: Student @ University of Waterloo
email: contact@pitrick.link
website: https://pitrick.link

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: pi_trick
github_username:  Pitrick3141
instagram_username: yichen314159
linkedin_username: yichenwang3141

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yichen Wang. I am currently studying as a 2A Honours Computer Science Student in University of Waterloo. I am interested in artificial intelligence, web development and game development.

  My most skilled fields are: <mark>Algorithms</mark>, <mark>Web Development</mark> and <mark>Game Design</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Full-Stack Software Developer
        link: https://nutralabcorp.com/
        link_text: Visit Company Website
        caption: Nutralab Corp., Toronto, Ontario, Canada
        sub_title: May 2024 - August 2024
        description: | # this will include new lines to allow paragraphs
          Developed the <mark>Vue.js</mark> Frontend of Inventory Management System for real-time inventory and transactions display, analysis and operations.

          Developed the Backend of Inventory Management System using <mark>MySQL</mark> and <mark>Flask</mark> for data storage and provide APIs for other company departments.

          Coordinated with other company departments and develop features that satisfies different requirements.

          Integrated with <mark>Amazon Seller Central</mark> and other E-commerce platforms (<mark>Shopify</mark>, <mark>BigCommerce</mark> etc.) through APIs and perform data operations and analysis on one platform.

          Implemented backup and recovery mechanisms to protect against data loss and ensure continuity of operations in the event of system failures or disasters.

          Ensured overall performance and reliability of the system.

      - layout: left
        title: Backend Developer Intern
        caption: Yunqi Shanglian, Shenyang, Liaoning, China
        sub_title: July 2023 - August 2023
        description: | # this will include new lines to allow paragraphs
          Developed backend for a business management platform using <mark>JavaScript</mark> and <mark>REST API</mark> as a Backend Developer Intern.

          Learned about integration with LLM and Generative AI through provided APIs and I used Git for version control and deployed on development environment.

          Communication and Collaboration skills are also gained through the precious intership experience.

      - layout: left
        title: Research Paper Co-Author
        link: https://ieeexplore.ieee.org/document/9776296/
        link_text: View Paper on IEEE
        caption: Multi-Objective Optimization based on Role in Mentorship Mode
        sub_title: March 2022 - May 2022
        description: | # this will include new lines to allow paragraphs
          Implement E-CARGO model on <mark>Java</mark> and write scripts to automate data generation and process using <mark>C++</mark>

          Analyze and visualize collected data using Microsoft Excel and make charts for the research paper.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: ROwO
        link: https://rowo.link
        link_text: Visit ROwO Website
        caption: Web development/Independent Fullstack Dev
        sub_title: A platform to share idea and opinion
        description: | # this will include new lines to allow paragraphs
          A website designed for sharing ideas and opinions freely and anonymously.

          Independently developed in spare time and is still under further development and enhancement.

          Technology stack:

          Build responsive web app using <mark>Vue.js</mark>, design user interface with <mark>Element Plus</mark>, <mark>CSS</mark> and <mark>Tailwind</mark>
          
          Host serverless backend on AWS Amplify to achieve continuous and synchronous deployment
          
          Integrate multi-factor Authentication system with AWS Congito and AWS AppSync for enhanced security
          
          Store data and media content in DynamoDB and S3 Bucket and communicate through <mark>GraphQL</mark>
          
          Distribute content globally through CloudFront CDN for faster response speed
          
          Provide secure SSL connection through HTTPS with Amazon Certificate Manager and Route53

      - layout: left
        title: iWant
        link: https://iwant.pitrick.link/
        link_text: View Demo Website
        caption: Artificial Intelligence/Web development
        sub_title: An AI powered schedule generator
        description: | # this will include new lines to allow paragraphs
          <mark> Participant project of 2024 United Hacks V2 Hackathon

          Technology stack:

          Build the backend using <mark>Python</mark> and deployed serverlessly on AWS Lambda
          
          Provide <mark>REST API</mark> through AWS API Gateway and use OpenAI API to process input data
          
          Beautify the React.js frontend and landing page using <mark>Bootstrap</mark> library for better user experience
          
          **The project is made by 4 students from University of Waterloo during the 2024 United Hacks V2 Hackathon on January, 2024**

      - layout: left
        title: QuicQ
        link: https://devpost.com/software/quicq
        link_text: View Repo on DevPost
        caption: Computer Vision/Artificial Intelligence/Web development
        sub_title: A queue optimization application based on computer vision
        description: | # this will include new lines to allow paragraphs
          A website designed for organizers and customers to optimize queue experience. 
          
          <mark>Participant and winner project of 2023 Hack the North</mark>

          Technology stack:

          **Frontend**: Build and host the responsive frontend dashboard web app using <mark>Vue.js</mark> and <mark>Vite</mark>,
          construct user friendly UI with <mark>Element+</mark> library and <mark>Tailwind</mark>, visualize data through <mark>Apache ECharts</mark>

          **Backend**: Backend is build by <mark>Flask</mark> and integrated through <mark>REST API</mark>

          **Computer Vision**: Utilize <mark>OpenCV</mark> to identify and count people in a queue and upload to the backend through API

          **AI Data Analysis**: Integrate <mark>Genesys</mark> to estimate realtime waiting time for queues
          
          **The project is made by 4 students from University of Waterloo during the 10th Hack the North hackathon on September,2023**

      - layout: left
        title: Chan's Poker Game
        link: https://github.com/Pitrick3141/chanscasino
        link_text: View Repo on GitHub
        caption: Fullstack Dev/Serverless/Continuous Deployment/AWS
        sub_title: An Online Minigame Project
        description: | # this will include new lines to allow paragraphs
          An online Minigame developed as my firsy fullstack development attempt. Able to signup/login and view records/statistics with cross-platform data sharing.

          Technology stack:
          
          **Frontend**: Frontend is built using <mark>Vue3+Vite</mark>, <mark>Element+</mark> and <mark>Tailwind</mark>

          **Hosting and Continuous Deployment**: The web app is hosted on <mark>AWS Amplify</mark> and deployed continuously through Github actions.

          **Authentication**: The backend authentication is achieved by <mark>AWS Cognito</mark>, with 2FA verifications enabled.

          **Data Interface**: Data are integrated through <mark>AWS AppSync</mark> and stored in <mark>AWS DynamoDB</mark>

          *Also developed as my Grade 12 Data Management ISP in 2023.*

      - layout: left
        title: RoAdv
        link: https://github.com/Pitrick3141/RoAdv
        link_text: View Repo on GitHub
        caption: Pygame/Linear Game Design
        sub_title: A Linear Advanture Game Project
        description: | # this will include new lines to allow paragraphs
          An animated linear advanture game based on <mark>Pygame</mark> where players fight monsters and save the village. 
          
          Multiple characters available with different abilities and strategies. There are also a variety of monsters and BOSS with unique skills.

          Fully customizable game experience where the difficulty can be adjusted easily.

          *Finished in Sep 2022*

      - layout: left
        title: Pixel Dungeon
        link: https://github.com/Pitrick3141/ISUProj
        link_text: View Repo on GitHub
        caption: Pygame/2D Game Design
        sub_title: A 2D Advanture Game Project
        description: | # this will include new lines to allow paragraphs
          An animated 2D advanture game based on <mark>Pygame</mark> where players defeat monsters, earn coins, unlock chests and escape from the dungeon. 
          
          Maps in the game are fully customizable. Player has multiple attack methods and full animations.

          *Finished in May 2022*

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: University of Waterloo
        link: https://uwaterloo.ca/
        link_text: School Website
        caption: Sep 2023 - Future
        sub_title: Honours Computer Science, Co-op
        quote: >
          In 1957, the University of Waterloo opened its doors to 74 engineering students with co-operative education as its cornerstone. Today, with more than 42,000+ students attending annually, Waterloo is #1 in Canada for experiential learning and employer-student connections. 
        description: | # this will include new lines to allow paragraphs
          I am currently studying in University of Waterloo in Honours Computer Science program with Co-op. I am currently doing my first Co-op work term in Nutralab Corp.

          Cumulative GPA: *91%*

      - layout: left
        title: Bishop Allen Academy
        link: https://www.tcdsb.org/o/bishopallen
        link_text: School Website
        caption: Feb 2021 - Jun 2023
        sub_title: High School Grade 10 - 12
        quote: >
          Bishop Allen is an excellent educational setting for the highly motivated, success-oriented student who enjoys learning. Our school motto is GAUDETE IN DOMINO â€“ Rejoice in the Lord. Bishop Allen Academy we strive to be a welcoming community that daily celebrates our calling to rejoice in the Lord. 
        description: | # this will include new lines to allow paragraphs
          Since I came to Canada in January 2021, I have been studying in BA. I learned more and deeper about computer science and Mathematics here. I was provided lots of opportunities to improve my skills of *programming* and *video editing*.

          I also participate many contests and competitions representing of BA. I am also active in contributing to my community and taking part in voluntary activities.

          I graduated from Bishop Allen Academy in 2023 with Top 6 average **99.13%**

      - layout: left
        title: Northeast Yucai Foreign Language School
        link: https://www.ycwgy.com/
        link_text: School Website
        caption: Sep 2017 - Jan 2021
        sub_title: High School Grade 7 - 10
        quote: >
          Northeast Yucai Foreign Language School is a Sino-foreign school jointly established in 1998 by Northeast Yucai School and Academy of Kansai Language School in Japan. It has 31 classes of junior and senior middle school, over 1200 students and a total of nearly a hundred Chinese and foreign teachers.
        description: | # this will include new lines to allow paragraphs
          I studied in NEYCFLS from Grade 7 to Grade 11 in China. It provides me with firm knowledge basis in many subjects and fields. Teachers there discovered and motivated my interest in Computer Science and Mathematics.

          I also spent time participating in many school activities. During Grade 10 and 11, I joined and worked in Student Union in the *Department of publicity*, in responsible for *photographing* and *social media operation*

  - title: Academic Awards & Achievements
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have attained several Academic Awards and Achievements both in China and Canada.

      Awards & Achievements acheved attained in Canada:
      - 2025 Excellent Academic standing and Term Distinction in 2A Term
      - 2024 Excellent Academic standing and Term Distinction in 1B Term
      - 2024 University of Waterloo [Faculty of Mathematics Promissory Scholarship](https://uwaterloo.ca/math/future-undergraduates/scholarships)
      - 2024 University of Waterloo [President's Scholarship of Distinction](https://uwaterloo.ca/undergraduate-entrance-awards/awards/university-waterloo-presidents-scholarship-distinction)
      - 2024 Excellent Academic standing and Term Distinction in 1A Term
      - 2023 [Hack the North](https://hackthenorth.com/#about) [10th iteration](https://hackthenorth2023.devpost.com/) - **Participant / [Winner Project](https://devpost.com/software/quicq)**
      - 2023 [CEMC](https://www.cemc.uwaterloo.ca/about-us/about-us.html) Euclid - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2023/2023EuclidResults.pdf) Group III (90/100) / Top 0.7%**
      - 2023 CEMC CCC Senior - **Distinction**
      - 2023 [COMC](https://cms.math.ca/competitions/comc/) - **[Qualified](https://cms.math.ca/competitions/comc/comc2023/advancing/) for [CMO](https://cms.math.ca/competitions/cmo/) (69.5/80) /
      [Award Winners](https://cms.math.ca/competitions/comc/comc2022/award-winners/) / 6th Place in Ontario Grade 12 / Bronze Medal in Toronto Grade 12**
      - 2022 CEMC CSMC - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2022/2022CxMCResults.pdf) Group III (49/60) / Top 0.3%**
      - 2022 [UWaterloo](https://uwaterloo.ca/chemistry/about-chemistry/community-outreach/chemistry-high-school-exams) Avogadro - **Distinction (81.41%) / National Top 5%**
      - 2022 [American Regions Mathematics League](https://www.arml.com/) - **Distinguished Participation**
      - 2022 CEMC Hypatia - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/sites/default/files/documents/2022/2022FGHResults.pdf) Group V (34/40) / Top 5%**
      - 2022 CEMC Euclid - **Distinction (84/100) / Top 3%**
      - 2022 [International Mathematical Modeling Challenge](https://www.immchallenge.org/Pages/About.html) - **Honorable Mention**
      - 2022 CEMC Fermat - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2022/2022FermatResults.pdf) Group III (138/150) / Top 0.3%**
      - 2021 [American Regions Mathematics League](https://www.arml.com/) - **Distinguished Participation**
      - 2021 CEMC CCC Junior - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2021/2021CCCResults.pdf) Group I (75/75) / Champion**
      - 2021 CEMC Cayley - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2021/2021CayleyResults.pdf) Group III (139/150) / Top 2%**
      - 2021 CEMC Euclid - **Distinction / [Honor Roll](https://cemc.uwaterloo.ca/contests/past_contests/2021/2021EuclidResults.pdf) (83/100) / Top 4%**

      Awards & Achievements achieved attained in China:
      - 2020 National English Proficiency Test for Secondary School Students - **National First Prize**
      - 2020 [NSDA](https://www.facebook.com/ChinaNSDA/) Public Forum Debate High School Div. Regional Championship - **Quarterfinalist**
      - 2020 [CCF](https://www.ccf.org.cn/en/About_CCF/About_CCF/) Certified Software Professional Senior - **First Prize**
      - 2019 CCF Certified Software Professional Senior - **Second Prize**
      - 2019 CCF Certified Software Professional Junior - **First Prize**
      - 2018 National Mathematics Innovative Application Contest - **Provincial First Prize**

      Other Academic Achievements:
      - **98%** in Elementary Algorithm Design and Data Abstraction **Advanced Level** (CS146) (Earned in 1B)
      - **96%** in Designing Functional Programs **Advanced Level** (CS145) (Earned in 1A)
      - School Nomination for **[UofT Lester B. Pearson Scholarship](https://future.utoronto.ca/pearson/about/)**
      - **100%** in Data Management (MDM4U1) (Earned in Grade 12)
      - **100%** in Religion (HRT4M1) (Earned in Grade 12)
      - **98%** in Physics (SPH4U1) (Earned in Grade 12)
      - **99%** in Introduction to Computer Studies (ICS4U1) (Earned in Grade 11)
      - **100%** in Calculus and Vectors (MCV4U1) (Earned in Grade 11)
      - **100%** in Advanced Functions (MHF4U1) (Earned in Grade 11)
      - **100%** in Physics (SPH3U1) (Earned in Grade 11)
      - **99%** in Functions (MCR3U1) (Earned in Grade 10)
      - **100%** in Principles of Mathematics (MPM2D1) (Earned in Grade 10)
      - Overall **7.5/9** in [IELTS](https://www.ieltscanada.ca/WhatIsIELTS) Test (Earned in Grade 10)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Computer Science and Mathematics, some of my other interests and hobbies are:
      - Photographing
      - Going to gym
      - Biking
      - Swimming
      - Gaming
      - Video Editing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
